### ISSUE TITLE
Raumplan lädt in der WebApp auf iOS nicht

### ISSUE THREAD

**Issue by Aruna-R6** [MCG-App/MCG-App#17]
In der Web-App sind in Beta und Vollversion die Raumpläne nicht nutzbar. Beim öffnen wird man Entwerfer auf die Startseite geschickt oder kriegt eine Fehler Meldung 
![85FD70F0-D1D0-49B1-A4E4-31BBBA1A6284](https://user-images.githubusercontent.com/118021125/201427125-08144af6-0db4-4b20-a6f8-01abcf835ff3.png)

**Comment by TheMelone2** [comment]
Hey
Danke für deinen Bugreport, ich leite das weiter :)

LG Jan Luca

**Comment by SLH335** [comment]
Moin, vielen Dank für deine Meldung. 
Das Problem ist mir auch schon aufgefallen, die Ursache kenne ich aber noch nicht. Ich konnte es bis jetzt nur auf iOS reproduzieren. Der Raumplan funktioniert mit Chromium-Browsern und Firefox auf Linux und Android.
Kann jemand versuchen, den Bug auf Windows und macOS zu reproduzieren?

**Comment by SLH335** [comment]
Auf macOS existiert das Problem nicht.

**Comment by SLH335** [comment]
Ich habe die SVGs mit dem Tool [SVGO](https://github.com/svg/svgo) optimiert und die [Beta-Web-App](https://mcg-app-beta.hafemann.xyz/) aktualisiert.

Auf meinem iOS-Gerät kann man den Raumplan jetzt sehen. Ist es bei dir auch so, @Aruna-R6?

Ich nehme an, dass der SVG-Viewer auf iOS nicht mit bestimmten Metadaten der SVG klargekommen ist, da diese mit Inkscape erstellt wurde. In der Optimierung mit SVGO werden diese Metadaten entfernt.

Beim Raumplan in der WebApp auf iOS scheint es jedoch noch weitere Bugs zu geben. Die Rauminfos werden beim Antippen eines Raums nicht angezeigt und die Grafik verschwindet, wenn man sie zu weit vergrößert. Lassen sich diese Probleme reproduzieren?

**Comment by Aruna-R6** [comment]
Problem ist Behoben vielen Dank und bei dem vergrößern ist die Anzeige Genau zu jedem Raum passend.

**Comment by SLH335** [comment]
Sehr schön. Ich habe die maximale Vergrößerung des Raumplans jetzt so begrenzt, dass die Grafik nicht mehr verschwindet.

Das Problem ist anscheinend vollständig behoben, deshalb schließe ich jetzt diesen Thread. Der Fix erreicht die nicht-beta WebApp auf [mcg-app.hafemann.xyz](https://mcg-app.hafemann.xyz/) in der nächsten Version v0.2.0.
