### ISSUE TITLE
Button zum Zurücksetzen der Filter im Vertretungsplan

### ISSUE THREAD

**Issue by WuerfelZocker** [MCG-App/MCG-App#19]
Wenn man viele unterschiedliche Filter🗃 eingestellt hat und alle entfernen möchte, muss man alle **manuell herauslöschen**. Um dieses Problem zu lösen, sollte es einen **Button** geben, der alle **Filter gleichzeitig zurücksetzen** kann. Dieser Button könnte über oder neben dem Speicherbutton positioniert werden.

**Comment by SLH335** [comment]
Gute Idee!
Ich habe einen Button, der die Filter zurücksetzt, links neben dem Speicher-Button hinzugefügt. Es sollte schon alles funktionieren. Ich veröffentliche später eine Beta-Version, in der man die Funktionalität testen kann.

**Comment by SLH335** [comment]
Die [Beta-Version](https://github.com/MCG-App/MCG-App/releases/tag/0.2.1-beta.1) mit dem neuen Button ist jetzt verfügbar.
